name: Build Windows Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '14.0'

    - name: Build the project
      run: |
        msbuild MapleStory.sln /p:Configuration=Release /p:WindowsSDKVersion=8.1 /p:VisualStudioVersion=14.0
